# Operaciones por capas...

In [27]:
import numpy as np
import tensorflow as tf
session = tf.Session()

$$X \in \mathbb R_{3 \times 4}$$

In [28]:
my_array = np.array([[1., 3., 5., 7.], [-2., 0., 7., 6.], [-6., -1., 0., 3.]])
my_array

array([[ 1.,  3.,  5.,  7.],
       [-2.,  0.,  7.,  6.],
       [-6., -1.,  0.,  3.]])

In [29]:
x_vals = np.array([my_array, my_array + 1])
x_vals

array([[[ 1.,  3.,  5.,  7.],
        [-2.,  0.,  7.,  6.],
        [-6., -1.,  0.,  3.]],

       [[ 2.,  4.,  6.,  8.],
        [-1.,  1.,  8.,  7.],
        [-5.,  0.,  1.,  4.]]])

In [30]:
x_data = tf.placeholder(tf.float32, shape = (3, None))

* $m_1 \in \mathbb R^4$
* $m_2, a_1 \in \mathbb R$

In [31]:
m1 = tf.constant([[1.], [0.], [-2.], [5.]])
m2 = tf.constant([[7.]])
a1 = tf.constant([[15.]])

$$[(X\cdot m_1)\cdot m_2] + a1$$

In [32]:
prod_1 = tf.matmul(x_data, m1)
prod_2 = tf.matmul(prod_1, m2)
add_1 = tf.add(prod_2, a1)

In [33]:
for x_val in x_vals:
    print(session.run(add_1, feed_dict = {x_data: x_val}))

[[197.]
 [113.]
 [ 78.]]
[[225.]
 [141.]
 [106.]]
