# Cómo trabajar con matrices...

In [12]:
import tensorflow as tf
session = tf.Session()

## 1. Cómo crear matrices...

In [24]:
identity = tf.diag([1., 1., 1., 1.])
print(session.run(identity))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
A = tf.truncated_normal([3, 4])
print(session.run(A))

[[ 1.0667627  -0.09428748 -0.51223785 -0.00180797]
 [-0.04794319  0.99348897  1.7972026  -0.97237366]
 [ 1.4201202   0.20142326  0.40856     0.3340371 ]]


In [19]:
B = tf.fill([3, 4], 1993.)
print(session.run(B))

[[1993. 1993. 1993. 1993.]
 [1993. 1993. 1993. 1993.]
 [1993. 1993. 1993. 1993.]]


In [16]:
C = tf.random_uniform([4, 3])
print(session.run(C))

[[0.280918   0.9158882  0.4457444 ]
 [0.7063762  0.70566213 0.09161031]
 [0.44235623 0.34740472 0.6760999 ]
 [0.7425343  0.5665271  0.43595946]]


In [17]:
import numpy as np
data = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
D = tf.convert_to_tensor(data)
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 2. Operar con matrices...

In [20]:
print(session.run(A + B))

[[1992.9943 1992.3866 1992.479  1992.8684]
 [1992.4618 1992.6202 1994.3893 1992.8148]
 [1992.3561 1993.2556 1991.7485 1994.3857]]


In [21]:
print(session.run(B - B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
print(session.run(tf.matmul(A, C)))

[[ 1.4703112  1.1958556  1.4853566]
 [-1.7715394 -2.1346297 -2.128488 ]
 [ 1.6560166  1.0422136  1.7711042]]


In [27]:
print(session.run(tf.matmul(A, identity)))

[[ 1.2274985   1.0373735  -0.19898921  0.10276604]
 [-0.06979556  0.10167833  0.4308807  -1.6737107 ]
 [-0.2734195  -1.3331542   1.0197338  -1.2158253 ]]


## 3. Traspuesta, determinante e inversa de una matriz...

In [28]:
print(session.run(tf.transpose(D)))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [29]:
print(session.run(tf.transpose(A)))

[[ 0.00832898  0.8392306   1.0469161 ]
 [-0.33714274 -0.94763464 -0.8035634 ]
 [ 0.03024225 -0.3367529  -0.45595017]
 [-0.01328415  0.07438318  0.786028  ]]


In [30]:
print(session.run(tf.matrix_determinant(D)))

6.66133814775094e-16


In [31]:
E = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -6., -1], [0., 5., -3.]]))
print(session.run(tf.matrix_determinant(E)))

-40.0


In [33]:
print(session.run(tf.matrix_inverse(E)))

[[-0.575 -0.525 -0.4  ]
 [ 0.225  0.075  0.2  ]
 [ 0.375  0.125  0.   ]]


In [34]:
print(session.run(tf.matmul(E, tf.matrix_inverse(E))))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.55111512e-17  1.00000000e+00]]


## 4. Descomposición...

In [36]:
print(session.run(tf.cholesky(identity)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. Valores y vectores propios...

In [39]:
# Valores propios...
print(session.run(tf.self_adjoint_eigvals(E)))

[-10.24888536  -0.66882335   2.91770871]


In [41]:
# Valores Propios y Vectores propios...
print(session.run(tf.self_adjoint_eig(E)))

(array([-10.24888536,  -0.66882335,   2.91770871]), array([[ 0.21442787,  0.60489799, -0.76688924],
       [ 0.80402486,  0.3364893 ,  0.49022339],
       [-0.55458517,  0.72171557,  0.41420034]]))
