# Funciones de activación...

In [6]:
import tensorflow.nn as nn
import tensorflow as tf
session = tf.Session()

## Función ReLU...
* Contínua
* No derivable

$$ f(x) = max(0, x)$$

In [7]:
print(session.run(nn.relu([-5., 5., 15.])))

[ 0.  5. 15.]


$$ f(x) = min(max(0, x), 6)$$

In [8]:
print(session.run(nn.relu6([-5., 5., 15.])))

[0. 5. 6.]


## Función sigmoide (logística)...
* Contínua
* Derivable
* Rango de valores (0, 1)

$$f(x) = \frac{1}{1 + e^{-x}}$$

In [9]:
print(session.run(nn.sigmoid([-2., -1., 0., 1., 2.])))

[0.11920292 0.26894143 0.5        0.7310586  0.880797  ]


## Función Tangente Hiperbólica...
* Continua 
* Derivable
* Rango de valores (-1, 1)

$$f(x) = tanh(x) = \frac{e^x - e^-x}{e^x + e^-x}$$

In [10]:
print(session.run(nn.tanh([-2., -1., 0., 1., 2.])))

[-0.9640276 -0.7615942  0.         0.7615942  0.9640276]


## Función softsign...
* Versión continua de la función sign
* No es derivable

In [11]:
print(session.run(nn.softsign([-2., -1., 0., 1., 2.])))

[-0.6666667 -0.5        0.         0.5        0.6666667]


$$f(x) = \frac{x}{|x| + 1}$$

## Función softplus...
* Versión continua y derivable de la función ReLU

$$f(x) = ln(e^x + 1)$$

In [12]:
print(session.run(nn.softplus([-2., -1., 0., 1., 2.])))

[0.12692805 0.31326166 0.6931472  1.3132616  2.126928  ]


## Función ELU (Exponencial Lineal Unitaria)...
* Similar a la soft plus
* Asíntota horizontal tiende a -1

$$f(x) = e^x + 1 \ si x < 0$$
$$f(x) = x \ si x \geq 0$$

In [13]:
print(session.run(nn.elu([-2., -1., 0., 1., 2.])))

[-0.86466473 -0.63212055  0.          1.          2.        ]


## Gráfico de las funciones de activación...
![](../../resources/02-act.png)
![](../../resources/03-act.png)